### ISSUE TITLE
Problem building Mirakel (generate_v14_compatible_resources.py Error:(37, 0) CreateProcess error=193, %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by MarsLoop** [MirakelX/mirakel-android#623]
I've can't get to build Mirakel, after other problems I've gotten to the point that is say:

Error:(37, 0) CreateProcess error=193, %1 is not a valid Win32 application

Which has to do with this line:
def script = (rootDir.toString()+"/build/scripts/generate_v14_compatible_resources.py --res-dir "+res_dir+" --res-v14-compatibility-dir "+res_v14_dir+"").execute()

I don't need API 14 anyway, how can I make it build for API17 at least?

**Comment by harit222** [comment]
I am also getting the same problem. Not sure what is the issue here. I would like to get started with development but it seems like I cant load this project at all in Android studio.

**Comment by weiznich** [comment]
This is caused by a missing python installation on windows. I added a quick an dirty workaround for this. (Basically don't use the python script on windows and simply set the sdk level to 17)
See the [documentation](https://github.com/MirakelX/mirakel-android/blob/master/build/scripts/generate_v14_compatible_resources.py#L7-L20) in the python script why we must use it to support older android versions.
